### ISSUE TITLE
OPropertiesI: refBaseRoleClassPath - DataProperty (?)

### ISSUE THREAD

**Issue by olga-kovalenko** [i40-Tools/vocabularies#10]
I would say refBaseRoleClassPath should be rather Data property, than the Object property

**Comment by igrangel** [comment]
[Here](https://github.com/i40-Tools/vocabularies/blob/d6e719b902d1843b870b0e51d8d2771aeaa6fddb/AutomationML/amlOnto.owl#L882) is the hasRefBaseRoleClassPath property which is a Data Property, where did you find refBaseRoleClassPath ?

**Comment by olga-kovalenko** [comment]
That was in the original file I took as a starting point to work on. At line 100. (should be a file version 2 updates before). But I deleted this object property while doing my updates, so its not there anymore. Unless you want to restore it, we can close the issue, i guess :)

**Comment by igrangel** [comment]
Yes, we will close, just from now on linking to the specific line will improve our productivity :+1:
