### ISSUE TITLE
OPropertiesI: hasExternalInterface should be subproperty of hasInterface (?)

### ISSUE THREAD

**Issue by olga-kovalenko** [i40-Tools/vocabularies#12]
In my opinion, we don't really need this property because each "ExternalInterface" is an "InterfaceClass", which means we can use "hasInterface" and its subclasses instead of "hasExternalInterface".

Or do we need further specification here for some purpose?

**Comment by igrangel** [comment]
Yes, I agree. Let's just have the `hasInterface ` property with range `InterfaceClass`.
