### ISSUE TITLE
OPropertiesI: smth strange with unitExternalInterface

### ISSUE THREAD

**Issue by olga-kovalenko** [i40-Tools/vocabularies#14]
I am not sure what this propery stays for, i.e., what is the intended semantics here...

**Comment by igrangel** [comment]
Could you point to the line of code?

**Comment by olga-kovalenko** [comment]
That was in the original file (a file version 2 updates before from the current ontology), which I took as a starting point for my updates. At line 172. I might have deleted this property during my updates, so its not there any more. 

But I attach the original file in case you would like to have a look.
[amlOnto_origin.txt](https://github.com/i40-Tools/vocabularies/files/449970/amlOnto_origin.txt)

**Comment by igrangel** [comment]
Let's continue with the file we have now.
