### ISSUE TITLE
OPropertiesI: NamingConvension

### ISSUE THREAD

**Issue by olga-kovalenko** [i40-Tools/vocabularies#2]
We should agree on a consistent way to name classes and properties. E.g., now we have 2 conventions used in a mixed way:
- hasAttribute, has Project, isPartOf, etc.
- interfaceClassAttribute, interfaceClassIsPartOf, etc.

This is a bit confusing... Shall we agree on one? I like much more the 1st one, where the properties have "verbs-like" names and classes are nouns. What do you think?

**Comment by igrangel** [comment]
For the first as you said is clear. Let us use Camell notation that is recommended as a good practice for design. Second, for those properties that the name is long, e.g., interfaceClassAttribute, what do you think, hasInterfaceClassAttribute? or we use hasInterfaceCA and in the annotations, i.e., skos:prefLabel we include hasInterfaceClassAttribute?

**Comment by igrangel** [comment]
For the naming convention of properties we follow that if the property has more that four units of semantic in the name then we shorten the name using abbreviations at the end. For example, hasMoreThanFourUnits -> hasMoreThanFU. In addition, we include the complete name in the skos:altLabel property.

**Comment by olga-kovalenko** [comment]
I would rather go for having a meaningful name, even if its a long one. Like hasMoneThan4Units in your example :) But if you sure, this is a good practice, then ok, let's do it. We will need this only for a couple of cases anyway, i guess.
