### ISSUE TITLE
Seperate IEC 62264 and RAMI

### ISSUE THREAD

**Issue by markusgraube** [i40-Tools/vocabularies#23]
I think it would be better to seperate the RAMI mapping from the core IEC62264 vocabulary. So keep all vocabularies in its own file and then have mapping file which maps concepts between RAMI, 62264, 61512 etc.

**Comment by igrangel** [comment]
They are separated now. [RAMI](https://github.com/i40-Tools/vocabularies/blob/master/RAMI/rami.ttl) and [IEC62264](https://github.com/i40-Tools/vocabularies/blob/master/IEC62264/iec62264.ttl). The property [`rami:hasRAMIHierarchyLevel`](https://github.com/i40-Tools/vocabularies/blob/47e26ab0a2daa89bcd0ab0a6cd47ffbc4406a5eb/RAMI/rami.ttl#L276) is used to connect the concepts with their respective Hierarchy Level.

**Comment by markusgraube** [comment]
Right, I exactly have this property  [`rami:hasRAMIHierarchyLevel`](https://github.com/i40-Tools/vocabularies/blob/47e26ab0a2daa89bcd0ab0a6cd47ffbc4406a5eb/RAMI/rami.ttl#L276) in mind, which I perhaps would move into a `rami-mapping` model. It's just because I am not sure if RAMI will survive and then we have dead links in the stable 62264 vocabulary.

However, in the end, it really doesn't matter much.

**Comment by igrangel** [comment]
If RAMI does not survive, the Standards and their relations will and we can always annotate the properties as deprecated and connected then with other properties.
