### ISSUE TITLE
OPropertiesI: Domain for hasProject

### ISSUE THREAD

**Issue by olga-kovalenko** [i40-Tools/vocabularies#4]
Currently the "hasProject" property has Domain="AdditionalInformation", although in the definition it is written "Related project for the CAEX file." Should it be rather changed to "CAEXFile"?

**Comment by igrangel** [comment]
The class `AdditionalInformation` is to model everything that is in the head of the AutomationML files. Therefore, it contains the Project, since maybe more metadata, i.e., properties can be added to the Project.

**Comment by olga-kovalenko** [comment]
Ok, then its clear, just wanted to double check :)
